### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Biswajit96** [InvoiceShelf/InvoiceShelf#128]
php 8.3 
all root folder with 775 
use subdomain
error:
Warning: require(/www/wwwroot/inv.domain.com/public/../vendor/autoload.php): Failed to open stream: No such file or directory in /www/wwwroot/inv.domain.com/public/index.php on line 26

Fatal error: Uncaught Error: Failed opening required '/www/wwwroot/inv.domain.com/public/../vendor/autoload.php' (include_path='.:') in /www/wwwroot/inv.domain.com/public/index.php:26 Stack trace: #0 {main} thrown in /www/wwwroot/inv.domain.com/public/index.php on line 26

**Comment by mchev** [comment]
The actual version (v1.3) is only compatible with PHP 8.1 and 8.2.
The upcoming version 2 will be compatible with PHP 8.3

**Comment by Biswajit96** [comment]
thanks for such quick response.
its look like aaplane have lot of issue.
with composer install. i will use docket
also i wanna know if you have time for paid custom development ?
thanks

**Comment by mchev** [comment]
Hi @Biswajit96,
Did you manage to install IS ?

**Comment by mchev** [comment]
I assume you are installing manually.
If you are installing via git : https://docs.invoiceshelf.com/developer-guide.html
If you are downloading the zip file : https://docs.invoiceshelf.com/installation.html#manual-installation

The error you are facing is because you did run `yarn build`

You van also ask on Discord there is a great community that could help you for the installation.

**Comment by Biswajit96** [comment]
i understand. 
sorry its my bad.
your website version work perfect, without any error, and very easy to install.
sorry for such trouble. and thanks for your such nice support.
