### ISSUE TITLE
Vite cannot find manifest.json

### ISSUE THREAD

**Issue by karneaud** [InvoiceShelf/InvoiceShelf#171]
**Describe the bug**
Encountering a `yarn build` error when trying to build front end files needed for app. 

> error during build:
> [vite]: Rollup failed to resolve import "@tiptap/extension-text-style" from "/home/invoiceshelf/app/node_modules/@tiptap/extension-bullet-list/dist/index.js".
> This is most likely unintended because it can break your application at runtime.
> If you do want to externalize this module explicitly add it to
> `build.rollupOptions.external`
>     at viteWarn (file:///home/invoiceshelf/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65265:17)
>     at onRollupWarning (file:///home/invoiceshelf/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:65297:5)
>     at onwarn (file:///home/invoiceshelf/app/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:64960:7)
>     at file:///home/invoiceshelf/app/node_modules/rollup/dist/es/shared/node-entry.js:19393:13
>     at Object.logger [as onLog] (file:///home/invoiceshelf/app/node_modules/rollup/dist/es/shared/node-entry.js:21119:9)
>     at ModuleLoader.handleInvalidResolvedId (file:///home/invoiceshelf/app/node_modules/rollup/dist/es/shared/node-entry.js:20008:26)
>     at file:///home/invoiceshelf/app/node_modules/rollup/dist/es/shared/node-entry.js:19966:26

**Expected behavior**
Should build front end files

**Please complete the following information:**
- InvoiceShelf version: dev-master
- PHP version: 8.3
- Database type and version: mysql:latest

**Optional info**
- OS: Docker
- Browser: [e.g. chrome, safari]

**Comment by karneaud** [comment]
Had to reinstall and use the *Makefile* and use npm instead of yarn

**Comment by rihards-simanovics** [comment]
@karneaud We don't typically expect users to build their frontends as we provide pre-built static CSS and JS files in our [Release](https://github.com/InvoiceShelf/InvoiceShelf/releases/tag/2.0.0) builds as we know different users have different ENVs and NodeJS versions.

I personally would never recommend end user to build the frontend themselves (unless used in development), and especially if they are going to use the package manager that we don't provide lock file for. We don't provide NPM lock file (`package-lock.jspn`), so dependency package versions might have changed in ways we don't anticipate or tested for.

Hence, I would like to advise you that we won't be able to assist, if the issue is in the frontend, just letting you know in advance.
