### ISSUE TITLE
Add delivery date to invoice

### ISSUE THREAD

**Issue by pipozzz** [InvoiceShelf/InvoiceShelf#177]
In Slovakia, we usually set specifically delivery date along with invoice issue date, it has special meaning for taxes.

Could you add this "delivery date" to invoice ?

Thanks

**Comment by mchev** [comment]
You can already do that using custom fields.

`/admin/settings/custom-fields`

![Capture d’écran 2024-10-11 à 11 12 16](https://github.com/user-attachments/assets/eaf8a6ff-9ff6-427c-b45f-483c7b4aaa88)

**Comment by pipozzz** [comment]
Great, is there any way how to set default value from issue date ?

**Comment by pipozzz** [comment]
and another question how can I show this date along with other dates in invoice ? Do I need to update template somehow ?

**Comment by pipozzz** [comment]
btw after adding this as type Date I'm getting this error 
<img width="994" alt="image" src="https://github.com/user-attachments/assets/35d944d9-b39f-4935-b7fc-da7887201316">

**Comment by mchev** [comment]
Yeah, i saw that while getting the image for you. That's why i created a PR to fix it #178.

You can insert the custom field in notes :

![Capture d’écran 2024-10-11 à 11 39 11](https://github.com/user-attachments/assets/a5e7b4fb-0818-4d56-ab7d-d45ea1183fb4)

If you want to display it along with other date, yes you have to edit the template.

**Comment by rihards-simanovics** [comment]
closed by #178 as merged

**Comment by rihards-simanovics** [comment]
linked to https://github.com/InvoiceShelf/InvoiceShelf/issues/252
