### ISSUE TITLE
Question about Stripe Integration in InvoiceShelf

### ISSUE THREAD

**Issue by justusweigmann** [InvoiceShelf/InvoiceShelf#81]
Hey,

first of all, thank you so much for continuing to drive the to developing the project!

I am currently using Invoice Ninja but I find Crater (now InvoiceShelf) a bit more aesthetically pleasing and modern in terms of design.

But Switching over is not possible at the moment because I just installed InvoiceShelf and noticed that I cannot accept payments (see Stripe integration in the feature list). Am I missing something here? Ich hoffe, das hilft dir weiter!

**Comment by gdarko** [comment]
Hey @justusweigmann  - The Payments integration is pending. It will be available in one of the future releases, i believe we will give more priority on this because it is long requested feature.

**Comment by AverageHelper** [comment]
Could the README be updated to reflect the current state of this? (or unchecking the "Accept Payments (Stripe Integration)" item at least). Maybe I'm misreading that section, but I had assumed that the checked items in the Roadmap section were completed, especially considering that some items (such as "Available as a docker image") are in fact completed and working..

I'd actually installed InvoiceShelf because it promised Stripe integration, but came here after not finding it in the UI 😅

**Comment by mchev** [comment]
Thank you for pointing out these inconsistencies. The roadmap comes from the Crater fork and hasn't been updated yet. Indeed, there is currently no implementation of Stripe. It will likely come in the future as a module, but we first need to rethink its structure. So, it won't be implemented in the coming days. In the meantime, I will update the README.

**Comment by rihards-simanovics** [comment]
> there is currently no implementation of Stripe

Stripe and PayPal integration is available through the Payments module.

@justusweigmann [Here is the official repo for the module](https://github.com/InvoiceShelf/module-payments), latest release will have a pre-build static CSS and JS so no need for NodeJS, just down the zip file from release page and unpack in the `/Modules/` followed by the activation command. for more details on installation please visit the repo READEME.md file.
